buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.1'
        //classpath 'com.android.tools.build:gradle:8.13'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

plugins {
    id 'com.google.gms.google-services' version '4.4.2' apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}

// --- Globális beállítások az összes Flutter pluginhoz ---
subprojects {
    project.tasks.withType(JavaCompile).configureEach {
        // Eltünteti a "source value 8 is obsolete" figyelmeztetéseket
        options.compilerArgs << "-Xlint:-options" 
    }
    project.tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        // Kényszerítjük, hogy minden külső csomag is Java 17-et használjon Kotlinhoz
        kotlinOptions.jvmTarget = "17"
    }
    //hogy a dependecyk is jó java verzióban menjenek
    if (project.name != "app") {
        project.afterEvaluate {
            if (project.hasProperty('android')) {
                project.android {
                    compileOptions {
                        sourceCompatibility = JavaVersion.VERSION_17
                        targetCompatibility = JavaVersion.VERSION_17
                    }
                }
            }
        }
    }
}